### ISSUE TITLE
invalid characters for a local volume name error, in volumes of proxy/api in docker-compose.yml

### ISSUE THREAD

**Issue by liuchong** [sourcelair/ceryx#5]
Creating ceryx_proxy_1
ERROR: proxy/nginx/lualib includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

Got above error, using the below link to be fixed:

> https://github.com/dogdep/dogpro/issues/6

**Comment by akalipetis** [comment]
Hello @liuchong, can you please post your `docker-compose.yml` file? This seems like an error in your Docker Compose config file and not of Ceryx itself.

**Comment by liuchong** [comment]
``` yaml
proxy:
  extends:
    file: base.yml
    service: proxy
  build: proxy
  ports:
   - "8888:80"
   - "5555:5555"
   - "6379:6379"
  volumes:
   - ./proxy/nginx/conf:/opt/openresty/nginx/conf
   - ./proxy/nginx/lualib:/opt/openresty/nginx/lualib
   - ./proxy/nginx/sites-enabled:/opt/openresty/nginx/sites-enabled
   - ./proxy/nginx/sites-available:/opt/openresty/nginx/sites-available
api:
  extends:
    file: base.yml
    service: api
  build: api
  net: container:proxy
  volumes:
   - ./api/ceryx:/ceryx/ceryx
   - ./api/bin:/ceryx/bin
redis:
  image: redis
  net: container:proxy
```

Above is the working one for me, I've changed the:
```
volumes:
   - proxy
```
to:
```
volumes:
   - ./proxy
```
